### ISSUE TITLE
Telegram-Bot does not reply although saying: "Telegram-Skill on Mycroft Unit "Core" is loaded and ready to use!"

### ISSUE THREAD

**Issue by SteveJos** [luke5sky/telegram-skill#14] opened 2020-10-09 08:59 UTC
The bot was properly installed and configured. In the logs the following error shows up:

`
2020-10-09 08:56:11.406 | ERROR    |    25 | telegram.ext.dispatcher | No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 425, in process_update
    handler.handle_update(update, self, check, context)
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/telegram/ext/handler.py", line 145, in handle_update
    return self.callback(update, context)
  File "/opt/mycroft/skills/telegram.luke5sky/__init__.py", line 109, in TelegramMessages
    msg = update.message.text
AttributeError: 'CallbackContext' object has no attribute 'message'
`

**Comment by luke5sky** [comment] 2020-10-12 07:14
Hi,

on what system/OS is mycroft running? (Mark 1, Ubuntu, etc...)

**Comment by SteveJos** [comment] 2020-10-13 09:47
@luke5sky Hey I am using the latest Docker from: https://hub.docker.com/r/mycroftai/docker-mycroft/dockerfile on a SynologyNAS. Except the Telegram plugin everything else is working fine...

**Comment by luke5sky** [comment] 2020-10-13 13:19
Thank you, I was able to reproduce this issue.
 I am trying to fix this as soon as possible.

Regards

**Comment by luke5sky** [comment] 2020-10-14 08:44
due to a new version of python-telegram-bot this skill was broken, the newest commit should work now.
please delete/remove the skill installed and reinstall it with this command:
mycroft-msm --latest install https://github.com/luke5sky/telegram-skill

i made a pull-request to update the skill in the mycroft skills repo (https://github.com/MycroftAI/mycroft-skills/pull/1405).
as soon as this is merged into master from the mycroft team you may also install this via the skills store or without the --latest flag.

if you got time to test this, i would appreciate it.

**Comment by luke5sky** [comment] 2020-10-19 09:30
No answear, should be fixed now -> closing

**Closed as completed by luke5sky** 2020-10-19 09:30 UTC
Labels: issue
